services:
    app.admin.transportadora:
        class: AppBundle\Admin\TransportadoraAdmin
        arguments: [~, AppBundle\Entity\Transportadora, SonataAdminBundle:CRUD]
        tags:
            - { name: sonata.admin, manager_type: orm, group: Frete, label: 'Transportadora', label_translator_strategy: sonata.admin.label.strategy.underscore }
        public: true
        calls:
            - [ setTranslationDomain, [ "AppBundle" ] ]

    app.admin.faixa_entrega:
        class: AppBundle\Admin\FaixaEntregaAdmin
        arguments: [~, AppBundle\Entity\FaixaEntrega, SonataAdminBundle:CRUD]
        tags:
            - { name: sonata.admin, manager_type: orm, group: Frete, label: 'Faixas de Entrega', label_translator_strategy: sonata.admin.label.strategy.underscore }
        public: true
        calls:
            - [ setTranslationDomain, [ "AppBundle" ] ]

    app.admin.calculo_frete:
        class: AppBundle\Admin\CalculoFreteAdmin
        arguments: [~, AppBundle\Entity\CalculoFrete, AppBundle:CalculoFreteAdmin]
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin, label: CalculoFrete, label_translator_strategy: sonata.admin.label.strategy.underscore }
        public: true
        calls:
            - [ setTranslationDomain, [ "AppBundle" ] ]

    validator.cep_no_intervalo:
        class: AppBundle\Validator\Constraints\CepNoIntervaloValidator
        arguments: ['@doctrine.orm.entity_manager']
        tags:
            - { name: validator.constraint_validator, alias: cep_no_intervalo }
    
    app.faixa_entrega_repository:
        class: AppBundle\Repository\FaixaEntregaRepository
        factory: ['@doctrine.orm.entity_manager', getRepository]
        arguments:
            - AppBundle\Entity\FaixaEntrega
            
    app.calcula_frete_service:
        class: AppBundle\Utils\CalculaFreteService
        arguments: ['@app.faixa_entrega_repository', '@security.token_storage', '@event_dispatcher']
    
    app.valida_request_calcula_frete:
        class: AppBundle\Utils\ValidaRequestCalculoFreteService
        arguments: ['@validator']
        
    app.calculo_frete_log_listener:
        class: AppBundle\Listener\CalculoFreteLogListener
        arguments: ['@doctrine.orm.entity_manager']
        tags:
            - { name: kernel.event_listener, event: calculofrete.done, method: onCalculoFrete }
