<?php

namespace AppBundle\Repository;

/**
 * FaixaEntregaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FaixaEntregaRepository extends \Doctrine\ORM\EntityRepository
{
    const IS_ENABLED = TRUE;

    /**
     * 
     * @param int $cep
     * @return QueryBuilder
     */
    public function getFretePorCep($cep)
    {
        $query = $this->createQueryBuilder('f');
        $query
            ->innerJoin('f.transportadora', 't')
            ->andWhere(
                $query
                    ->expr()
                    ->lte('f.cepInicial', ':cep')
            )
            ->andWhere(
                $query
                    ->expr()
                    ->gte('f.cepFinal', ':cep')
            )
            ->andWhere(
                $query
                    ->expr()
                    ->eq('t.isAtiva', ':isativa')
            )
            ->setParameter('cep', $cep)
            ->setParameter('isativa', self::IS_ENABLED)
            ->orderBy('f.valorQuilo')
        ;
        
        return $query;
    }
}
