<?php

namespace AppBundle\Repository;

/**
 * FaixaEntregaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FaixaEntregaRepository extends \Doctrine\ORM\EntityRepository
{
}
