version: '2.1'

services:
    php:
        build: php7-fpm
        links:
            - db:mysqldb
        volumes:
            - ${SYMFONY_APP_PATH}:/var/www/symfony
            - ./logs/symfony:/var/www/symfony/app/logs
        depends_on:
            db:
                condition: service_healthy
    nginx:
        build: nginx
        ports:
            - 8888:80
        volumes_from:
            - php
        volumes:
            - ./logs/nginx/:/var/log/nginx
        links:
            - db
        depends_on:
            - db
    db:
        image: mysql
        volumes:
            - "./.data/db:/var/lib/mysql"
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        healthcheck:
            test: exit 0
