branches:
  only:
    - master

language: php

php:
  - '5.3'
  - '5.4'
  - '5.5'
  - '5.6'

before_script:
  - cp app/config/parameters.yml.dist app/config/parameters.yml
  - curl -s http://getcomposer.org/installer | php --
  - php composer.phar install
  - php app/console doctrine:database:create --env=test
  - php app/console doctrine:schema:create --env=test
